package com.alvexo.adminportal.entity;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    PAYMENT_RECEIVED,
    SUBSCRIPTION_EXPIRING,
    REFERRAL_BONUS,
    REVIEW_RECEIVED,
    WORKSHOP_REGISTRATION_APPROVED,
    WORKSHOP_REGISTRATION_REJECTED,
    WORKSHOP_REGISTRATION_INFO_REQUESTED,
    WORKSHOP_VERIFICATION_APPROVED,
    WORKSHOP_VERIFICATION_REJECTED,
    WORKSHOP_VERIFICATION_INFO_REQUESTED,
    GENERAL
}
